// ANALYSIS
USE DATABASE RESTAURANT_WEATHER;
USE SCHEMA DWH;

// CHECK RANGE OF DATES
SELECT MIN(DATE), MAX(DATE)
FROM DWH.FACT_CLIMATE_REVIEW;

// PER DAY, BUSINESS, CALC AVERAGE RATING
SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
FROM DWH.FACT_CLIMATE_REVIEW 
GROUP BY DATE, BUSINESS_ID
LIMIT 1000;


// --------------------------------------
// CORRELATION ON AVERAGE TEMPERATURE
SELECT CORR(AVG_STARS, (T.MIN + T.MAX)/2)
FROM (
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
    FROM DWH.FACT_CLIMATE_REVIEW 
    GROUP BY DATE, BUSINESS_ID
  ) AS R
JOIN DWH.DIM_TEMPERATURE T ON R.DATE = T.DATE
JOIN DWH.DIM_PRECIPITATION P ON R.DATE = P.DATE;

// --------------------------------------
// CORRELATION ON PRECIPITATION
SELECT CORR(AVG_STARS, P.PRECIPITATION)
FROM (
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
    FROM DWH.FACT_CLIMATE_REVIEW 
    GROUP BY DATE, BUSINESS_ID
  ) AS R
JOIN DWH.DIM_TEMPERATURE T ON R.DATE = T.DATE
JOIN DWH.DIM_PRECIPITATION P ON R.DATE = P.DATE;

// --------------------------------------
// REGRESSION ON AVERAGE TEMPERATURE
SELECT regr_r2(AVG_STARS, (T.MIN + T.MAX)/2)
FROM (
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
    FROM DWH.FACT_CLIMATE_REVIEW 
    GROUP BY DATE, BUSINESS_ID
  ) AS R
JOIN DWH.DIM_TEMPERATURE T ON R.DATE = T.DATE;

// --------------------------------------
// REGRESSION ON PRECIPITATION
SELECT regr_r2(AVG_STARS, P.precipitation)
FROM (
    SELECT DATE, BUSINESS_ID, AVG(STARS) AS AVG_STARS, COUNT(*) AS NUM_REVIEWERS
    FROM DWH.FACT_CLIMATE_REVIEW 
    GROUP BY DATE, BUSINESS_ID
  ) AS R
JOIN DWH.DIM_PRECIPITATION P ON R.DATE = P.DATE;

// --------------------------------------
// REPORT
SELECT B.NAME, R.MIN_TEMPERATURE, R.MAX_TEMPERATURE, R.PRECIPITATION, R.STARS
FROM DWH.FACT_CLIMATE_REVIEW R
JOIN DIM_BUSINESSES B ON B.BUSINESS_ID = R.BUSINESS_ID;


